### ISSUE TITLE
Cineblog and other server 

### ISSUE THREAD

**Issue by hillhunter** [An0nimia/plugin.video.streamondemand.RMX#1]
Cb01 dont'work also serietvu and other server

**Comment by An0nimia** [comment]
In this last period all streaming site are closing and their domain change always. Anyway there are some others streaming site that are still working so the add on still working, no?

**Comment by hillhunter** [comment]
yes, work but i asking to you if you can update domain and make new realase with updated server. GOOD WORK MAN! The addon is very fast, and work for a lot of server.

**Comment by An0nimia** [comment]
A day I will work on it seriously.
